version: '2.4'
services:
  jamcaster:
    build:
      context: .
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - 5900:5900 # VNC
      - 3430:3430 # Jamviz
      - 22100:22100 # Jamulus JSON-RPC
