$instruments = {
  0: '-',
  1: 'Drums',
  2: 'Djembe',
  3: 'Electric Guitar',
  4: 'Acoustic Guitar',
  5: 'Bass Guitar',
  6: 'Keyboard',
  7: 'Synthesizer',
  8: 'Grand Piano',
  9: 'Accordion',
  10: 'Vocal',
  11: 'Microphone',
  12: 'Harmonica',
  13: 'Trumpet',
  14: 'Trombone',
  15: 'French Horn',
  16: 'Tuba',
  17: 'Saxophone',
  18: 'Clarinet',
  19: 'Flute',
  20: 'Violin',
  21: 'Cello',
  22: 'Double Bass',
  23: 'Recorder',
  24: 'Streamer',
  25: 'Listener',
  26: 'Guitar Vocal',
  27: 'Keyboard Vocal',
  28: 'Bodhran',
  29: 'Bassoon',
  30: 'Oboe',
  31: 'Harp',
  32: 'Viola',
  33: 'Congas',
  34: 'Bongo',
  35: 'Vocal Bass',
  36: 'Vocal Tenor',
  37: 'Vocal Alto',
  38: 'Vocal Soprano',
  39: 'Banjo',
  40: 'Mandolin',
  41: 'Ukulele',
  42: 'Bass Ukulele',
  43: 'Vocal Baritone',
  44: 'Vocal Lead',
  45: 'Mountain Dulcimer',
  46: 'Scratching',
  47: 'Rapping',
}
