= jamcaster
:collapsible:

Docker container to broadcast Jamulus sound to an Icecast server OR broadcast video to an RTMP server (e.g. Facebook Live, YouTube Live).

== Usage

[source,shell]
----
echo '
ICECAST_MOUNT_POINT=icecast://source:<passworld>@<host>:<port>/<mountpoint>
JAMULUS_SERVER=<host>:<port>
' > jamcaster.env

docker run -ti --rm --init --env-file=jamcaster.env ghcr.io/dtinth/jamcaster:main
----

.Docker compose
[%collapsible.result]
====
.docker-compose.yml
[source,yaml]
----
version: "2.4"
services:
  jamcaster:
    image: ghcr.io/dtinth/jamcaster:main
    environment:
      - ICECAST_MOUNT_POINT=icecast://source:<passworld>@<host>:<port>/<mountpoint>
      - JAMULUS_SERVER=<host>:<port>
----
====

== Environment variables

`ICECAST_MOUNT_POINT`::
*(Icecast mode)* The mount point to use for the Icecast server.
+
Example: `icecast://source:<password>@<host>:<port>/<mountpoint>`

`VIDEO_STREAM_TARGET`::
*(RTMP streaming mode)* The URL to use for streaming the RTMP server.
Setting this variable activates RTMP streaming mode and disables Icecast mode.
+
Example: `rtmp://a.rtmp.youtube.com/live2/<streamKey>`

`JAMULUS_SERVER`::
Jamulus server to connect to.
+
Example: `<host>:<port>`

`JAMULUS_CLIENT_INSTRUMENT`::
The instrument number to use for the Jamulus client. The list of available
instruments can be found https://github.com/jamulussoftware/jamulus/blob/417a9bc8c26cdf06fb301cdfaa96e3f875a52666/src/util.cpp#L893-L1037[here], where `None` is 0.
+
Example: `24` (streamer)

`JAMULUS_CLIENT_NAME`::
The name to use for the Jamulus client. The special token `%s` will be replaced by the current number of listeners.

== Links

* https://github.com/dtinth/jamcaster[Source code on GitHub]
